name: Sync to GitLab
on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gite.lirmm.fr/csp/choco-solver.git
          git push --mirror gitlab
